version: "3.3"
networks:
  sonarqube:
    driver: bridge
volumes: 
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
services:
  sonarqube:
    image: sonarqube:lts-community
    networks: 
      - sonarqube
    ports:
      - "9000:9000"
    environment: 
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes: 
      - "sonarqube_data:/opt/sonarqube/data"
      - "sonarqube_logs:/opt/sonarqube/logs"
      - "sonarqube_extensions:/opt/sonarqube/extentions"
      